(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function ba(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");}var da=ca(this);
function g(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:ba(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function c(){}c.prototype=a;return new c},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var fa={a:!0},p={};try{p.__proto__=fa;n=p.a;break a}catch(a){}n=!1}m=n?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}
var q=m,r=this||self;function t(a,c){a=a.split(".");var b=r;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===c?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=c};function ha(a){a=u(a,"autoplay-duration");return 0<a?a:29}function u(a,c){a=parseFloat(a.getAttribute(c));isFinite(a)||(a=29);return a};function v(a){var c=[],b=0,d;for(d in a)c[b++]=a[d];return c};var ia={ua:{value:!0,configurable:!0}};var w=Object,ja=w.freeze,x=[];Array.isArray(x)&&!Object.isFrozen(x)&&Object.defineProperties(x,ia);ja.call(w,x);function z(a,c){var b=r.performance;a={label:a,type:9,value:b&&b.now&&b.timing?Math.floor(b.now()+b.timing.navigationStart):Date.now()};c=c.google_js_reporting_queue=c.google_js_reporting_queue||[];2048>c.length&&c.push(a)};var A={},B=!1,C=!1;A.N=function(a){B||(B=!0,z("11",a))};A.O=function(a){C||(C=!0,z("12",a))};A.J=function(a,c,b){var d=c;d=void 0===d?r:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===b?0:b,value:d},c=c.google_js_reporting_queue=c.google_js_reporting_queue||[],2048>c.length&&c.push(a)};A.reset=function(a){C=B=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",A);t("gwd.rumUtil.logContentLoading",A.N);
t("gwd.rumUtil.logContentRendered",A.O);t("gwd.rumUtil.logTimingEvent",A.J);t("gwd.rumUtil.reset",A.reset);function D(a){(0,A.J)("gwd3dmodelviewer_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);window.Enabler&&(a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame"))}function E(a){window.Enabler&&(a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement"),F())}var G=0,H=0;function F(){var a=Math.floor(performance.now()/100);0==G&&(G=a);for(a-=G;H<=a;H++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var I={Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}};function J(a,c){return window.setTimeout(a,c)};function K(a,c,b){b=void 0===b?null:b;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,b);c.dispatchEvent(d)};var L=v({R:"animation-name",aa:"auto-rotate",W:"autoplay",$:"autoplay-duration",ba:"camera-orbit",ca:"camera-target",da:"environment-image",ea:"exposure",fa:"field-of-view",ka:"max-camera-orbit",la:"max-field-of-view",ma:"min-camera-orbit",na:"min-field-of-view",oa:"poster",pa:"reveal",qa:"shadow-intensity",ra:"shadow-softness",sa:"skybox-image",ta:"src"}).concat(v({S:"ar",T:"ar-modes",U:"ar-placement",V:"ar-scale",ja:"ios-src"})),ka=L.concat(v({ga:"gesture-cue-duration",ha:"gesture-cue-icon",ia:"gesture-cue-text"})),
M=180/Math.PI;function N(){var a=HTMLElement.call(this)||this;a.i=null;a.v=!1;a.G=!1;a.B=null;a.F=null;a.l="hotspot-"+(2147483648*Math.random()|0);a.j=!1;a.D=a.M.bind(a);a.H=!1;return a}var O=HTMLElement;N.prototype=ea(O.prototype);N.prototype.constructor=N;if(q)q(N,O);else for(var P in O)if("prototype"!=P)if(Object.defineProperties){var Q=Object.getOwnPropertyDescriptor(O,P);Q&&Object.defineProperty(N,P,Q)}else N[P]=O[P];f=N.prototype;
f.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));R(this)};f.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.m&&(clearTimeout(this.m),this.m=void 0)};
f.attributeChangedCallback=function(){R(this)};
f.handleEvent=function(a){var c=this,b=a.type,d=a.detail;switch(b){case "click":this.u&&a.target===this.h?a.stopPropagation():a.target&&la(a.target)?(a.stopPropagation(),ma(this,a.target)):S(this);break;case "camera-change":"user-interaction"===d.source&&(this.i&&this.i.parentNode&&this.i.parentNode.removeChild(this.i),S(this),na(this));a.stopPropagation();K("camera-changed",this,d);break;case "preload":case "load":this.classList.add("ready");T(this);break;case "model-visibility":if(!d.visible)return;
this.G&&(D(!1),this.G=!1,this.j=!0,oa(this),K("scene-rendered",this,null),U(this).dismissPoster());break;case "poster-dismissed":requestAnimationFrame(function(){K("poster-dismissed",c,null)})}window.Enabler&&(b===studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH?(U(this).setAttribute("touch-action","none"),Enabler.reportEngagement(),F()):b===studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH&&(U(this).setAttribute("touch-action","pan-y"),F()))};
function U(a){a.h||(a.h=a.ownerDocument.createElement("model-viewer"),a.h.setAttribute("camera-controls",""),a.h.setAttribute("interaction-prompt","none"),a.h.setAttribute("loading","eager"),a.h.setAttribute("data-js-focus-visible",""),a.h.setAttribute("touch-action","pan-y"),a.h.addEventListener("click",a),a.h.addEventListener("model-visibility",a),a.h.addEventListener("preload",a),a.h.addEventListener("load",a),a.h.addEventListener("camera-change",a),a.h.addEventListener("poster-dismissed",a),a.appendChild(a.h));
return a.h}function oa(a){if(a.hasAttribute("autoplay")){var c=U(a);c.pause();c.play();a=1E3*ha(a);0<=a&&J(function(){c.pause()},a)}}function R(a){a.m||(a.m=J(a.gwdLoad.bind(a),0))}
f.gwdLoad=function(){var a=this;this.m&&(clearTimeout(this.m),this.m=void 0);customElements.whenDefined("model-viewer").then(function(){var c=a.h?a.h.getAttribute("src"):null,b=V(a,"src",!0);if(b){b!==c&&(a.v=!1,a.classList.remove("ready"),a.G=!0,a.j=!1,D(!0));c=g(L);for(b=c.next();!b.done;b=c.next())b=b.value,"src"!==b&&V(a,b);a.h&&a.h.jumpCameraToGoal();a.syncHotspotsToViewer();a.i&&a.i.parentNode&&a.i.parentNode.removeChild(a.i);if(b=a.getAttribute("gesture-cue-icon")){a.i=a.ownerDocument.createElement("div");
a.i.classList.add("gesture-cue-container");c=a.ownerDocument.createElement("div");c.classList.add("gesture-cue-icon");c.style.backgroundImage='url("'+b+'")';b=u(a,"gesture-cue-duration");c.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";a.i.appendChild(c);if(c=a.getAttribute("gesture-cue-text"))b=a.ownerDocument.createElement("p"),b.classList.add("gesture-cue-text"),b.textContent=c,a.i.appendChild(b);a.appendChild(a.i)}}else T(a)})};f.gwdIsLoaded=function(){return this.v};
function V(a,c,b){b=void 0===b?!1:b;var d=a.getAttribute(c);null==d||b&&!d?a.h&&a.h.removeAttribute(c):U(a).setAttribute(c,d);return a.h?a.h.getAttribute(c):null}function T(a){a.v||(a.v=!0,K("ready",a))}function W(a){a.u&&(300<Date.now()-a.L?X(a,!1):requestAnimationFrame(function(){W(a)}))}function na(a){a.L=Date.now();window.Enabler&&Enabler.reportEngagement();a.u||X(a,!0);requestAnimationFrame(function(){W(a)})}
function X(a,c){c?(a.u=!0,document.addEventListener("mouseup",a.D),document.addEventListener("touchend",a.D),I.Rotate&&I.Rotate(),E(!0),K("interaction-start",a)):(a.u=!1,E(!1),K("interaction-end",a))}f.M=function(){this.u&&(X(this,!1),document.removeEventListener("mouseup",this.D),document.removeEventListener("touchend",this.D))};
function ma(a,c){S(a);var b=U(a).getElementsByClassName("hotspot");for(var d=-1,e=0;e<b.length;e++)if(b[e]===c){d=e;var h=a;if(c.ownerDocument&&c.ownerDocument.body){var l=c.getElementsByClassName("hotspot-annotation");if(0!==l.length){l=l[0];l.style.transform="";h=h.getBoundingClientRect();var k=l.getBoundingClientRect(),y=k.right;k=k.bottom;var Z=0,aa=0;y>h.right&&(Z=Math.round(h.right-y)-5);k>h.bottom&&(aa=Math.round(h.bottom-k)-5);l.style.transform="translate3d("+Z+"px, "+aa+"px, 0px)"}}c.classList.add("selected");
a.B=c}b=d;if(-1!==b){d=c.getBoundingClientRect();e=c.querySelector("h3");c=c.querySelector("p");c={name:"Hotspot"+b,index:b,screenX:Math.round(d.left+d.width/2),screenY:Math.round(d.top+d.height/2),title:e?e.textContent:"",description:c?c.textContent:""};if(window.Enabler&&(Enabler.reportEngagement(),b="Hotspot"+(b+1)+"Click",I[b]))I[b]();K("hotspot-clicked",a,c)}}function Y(a){a.C||(a.C=J(a.P.bind(a),0))}
f.P=function(){this.C&&(clearTimeout(this.C),this.C=void 0);var a=U(this).getCameraOrbit(),c=a.theta+"rad",b=a.phi+"rad";a=a.radius+"m";void 0!==this.A&&(c=this.A+"deg",this.A=void 0);void 0!==this.o&&(b=this.o+"deg",this.o=void 0);void 0!==this.s&&(a=this.s+"m",this.s=void 0);var d=U(this);d.cameraOrbit=c+" "+b+" "+a;this.H&&(this.H=!1,d.jumpCameraToGoal())};f.setYaw=function(a){this.j&&(this.A=a,this.H=!0,Y(this))};f.setTargetYaw=function(a){this.j&&(this.A=a,Y(this))};
f.setTargetPitch=function(a){this.j&&(this.o=a,Y(this))};f.incrementTargetPitch=function(a){this.j&&(this.o=void 0!==this.o?this.o+a:U(this).getCameraOrbit().phi*M+a,Y(this))};f.setTargetZoom=function(a){this.j&&(this.s=a,Y(this))};f.incrementTargetZoom=function(a){this.j&&(this.s=void 0!==this.s?this.s+a:U(this).getCameraOrbit().radius+a,Y(this))};f.setTargetPivot=function(a,c,b){this.j&&(U(this).cameraTarget=a+"m "+c+"m "+b+"m")};
f.setTargetLocalPan=function(a,c){if(this.j){var b=U(this),d=b.getCameraTarget().z;b.cameraTarget=a+"m "+c+"m "+d+"m"}};f.setMaterialColor=function(a,c,b,d){c=[c,b,d,1];b=U(this);b=g(b.model.materials);for(d=b.next();!d.done;d=b.next())if(d=d.value,d.name===a){d.pbrMetallicRoughness.setBaseColorFactor(c);break}};f.setMaterialClearCoat=function(){};f.playAnimation=function(a){var c=U(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.play()};
f.pauseAnimation=function(a){var c=U(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.pause()};f.setAnimationTime=function(a,c){var b=U(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.currentTime=c};f.incrementAnimationTime=function(a,c){var b=U(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.currentTime+=c};f.addHotspot=function(a,c,b,d){var e=U(this);a=pa({K:e,hotspotName:a,position:c+"m "+b+"m "+d+"m",normal:"",title:"",description:"",I:!0});e.appendChild(a)};
f.setHotspotInfoCard=function(a,c,b){var d=U(this);if(a=d.querySelector('div[slot="hotspot-'+a+'"]')){var e=a.getElementsByClassName("hotspot-annotation"),h=d.ownerDocument;0===e.length?(d=h.createElement("div"),d.classList.add("hotspot-annotation"),a.appendChild(d)):d=e[0];for(;d.firstChild;)d.removeChild(d.firstChild);a=h.createElement("h3");a.textContent=c;d.appendChild(a);c=h.createElement("p");c.textContent=b;d.appendChild(c)}};f.lookAtHotspot=function(){};f.lookAtHotspotIndex=function(){};
function S(a){a.B&&(a.B.classList.remove("selected"),a.B=null)}
function pa(a){var c=a.position,b=a.normal,d=a.title,e=a.description,h=a.I,l=a.K.ownerDocument,k=l.createElement("div");k.setAttribute("slot","hotspot-"+a.hotspotName);k.classList.add("hotspot");h&&k.setAttribute("info-card-hidden","");k.setAttribute("data-position",c);b&&k.setAttribute("data-normal",b);if(d||e)a=l.createElement("div"),a.classList.add("hotspot-annotation"),c=l.createElement("h3"),c.textContent=d,a.appendChild(c),d=l.createElement("p"),d.textContent=e,a.appendChild(d),k.appendChild(a);
return k}
f.syncHotspotsToViewer=function(){var a=U(this);if(a){for(var c=g(a.querySelectorAll(".hotspot")),b=c.next();!b.done;b=c.next())b=b.value,b.parentNode&&b.parentNode.removeChild(b);if(c=this.querySelector("gwd-3d-hotspot-container")){this.F&&(b=this.F,(b=b.ownerNode||b.owningElement||b)&&b.parentNode&&b.parentNode.removeChild(b),this.F=null,U(this).classList.remove(this.l));var d=c.getAttribute("up-image"),e=c.getAttribute("over-image"),h=c.getAttribute("down-image");b="";d&&(b+="model-viewer."+this.l+
' .hotspot { background: url("'+d+'") center / contain no-repeat; }');e&&(b+="model-viewer."+this.l+' .hotspot:hover { background: url("'+e+'") center / contain no-repeat; }');h&&(b+="model-viewer."+this.l+" .hotspot:active, model-viewer."+(this.l+' .hotspot.selected { background: url("')+h+'") center / contain no-repeat; }');d=c.getAttribute("width");e=c.getAttribute("height");if(d||e)b+="model-viewer."+this.l+" .hotspot {",d&&(b+="width: "+parseFloat(d)+"px; "),e&&(b+="height: "+parseFloat(e)+"px; "),
b+="}";d=c.getAttribute("background-color");e=c.getAttribute("font-color");h=c.getAttribute("border-color");if(d||e||h)b+="model-viewer."+this.l+" .hotspot-annotation {",d&&(b+="background-color: "+d+"; "),e&&(b+="color: "+e+"; "),h&&(b+="border-color: "+h+"; "),b+="}";b&&(U(this).classList.add(this.l),e=document,d=e.getElementsByTagName("head")[0],d||(h=e.getElementsByTagName("body")[0],d=e.createElement("head"),h.parentNode.insertBefore(d,h)),e=e.createElement("style"),e.textContent=b,d.appendChild(e),
this.F=e);b=0;c=g(c.children);for(d=c.next();!d.done;d=c.next())if(d=d.value,e=d.getAttribute("data-position")){h=d.getAttribute("data-normal")||"";var l=d.getAttribute("hotspot-name")||String(b),k=d.getAttribute("hotspot-title")||"",y=d.getAttribute("hotspot-description")||"";d=pa({K:a,hotspotName:l,position:e,normal:h,title:k,description:y,I:d.hasAttribute("info-card-hidden")});a.appendChild(d);b++}}}};function la(a){return a.classList&&a.classList.contains("hotspot")?!0:!1}
f.getSceneGraphModel=function(){return U(this).model};f.getCameraDetails=function(){var a=U(this).getCameraOrbit(),c=a.theta,b=a.phi;a=a.radius;var d=U(this).getCameraTarget();return{yaw:c*M,pitch:b*M,zoom:a,x:d.x,y:d.y,z:d.z}};da.Object.defineProperties(N,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ka}}});customElements.define("gwd-3d-model-viewer",N);}).call(this);
